# Generated by Django 5.2.5 on 2025-08-31 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=120)),
                ('age', models.IntegerField(verbose_name=django.core.validators.MinLengthValidator(0))),
                ('color', models.CharField(verbose_name=120)),
            ],
            options={
                'db_table': 'Cat',
            },
        ),
    ]
