# Generated by Django 5.2.5 on 2025-09-01 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cat_Collector_app', '0002_alter_cat_age_alter_cat_color_alter_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)]),
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cat_Collector_app.cat')),
            ],
        ),
    ]
