# Generated by Django 5.2.5 on 2025-09-01 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cat_Collector_app', '0003_alter_cat_age_toy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='toy',
            table='Toy',
        ),
    ]
