# Generated by Django 5.2.5 on 2025-09-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cat_Collector_app', '0004_alter_toy_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cat',
            table='cat',
        ),
        migrations.AlterModelTable(
            name='toy',
            table='toy',
        ),
    ]
