# Generated by Django 5.2.5 on 2025-09-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cat_Collector_app', '0005_alter_cat_table_alter_toy_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.IntegerField(),
        ),
    ]
